### ISSUE TITLE
D405 Camera frame coincides with the D435i while using Multi Camera Launch

### ISSUE THREAD

**Issue by hello-fazil** [hello-robot/stretch_web_teleop#74] opened 2024-07-11 19:10 UTC
This issue surfaced from this forum thread https://forum.hello-robot.com/t/stretch-3-gripper-camera-transform-issue/1022/6 where the user was having trouble with the D405 camera frame that gets attached to the D435i frame in the head while using the `multi_camera.launch.py` from `stretch_web_teleop` package. But this issue does not seem to happen while using the `multi_camera.launch.py` from the Stretch ROS2 's `stretch_core` package.

**Comment by hello-amal** [comment] 2024-07-12 00:20
This was resolved in one of the recent pushes (see [this file](https://github.com/hello-robot/stretch_web_teleop/blob/master/launch/multi_camera.launch.py)). The issue is that the earlier launchfile, in both `stretch_ros2` and `stretch_web_teleop`, included the realsense multicamera launch file, which published a static transform of 0 between the frames. Both repositories have now removed that dependence.

If they pull the latest code and re-build, it will be resolved.

**Closed by hello-amal** 2024-07-12 00:20 UTC
